---
# Note: Keep keys and envs in alphabetical order.
name: Check
# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
  schedule:
    - cron: 0 0 * * 1  # Run every Monday at 00:00 UTC
  workflow_dispatch:
    inputs:
      submodules:
        default: 'false'
        description: 'Whether to checkout submodules: true, false, or recursive'
        options:
          - 'false'
          - 'true'
          - recursive
        required: false
        type: choice
  workflow_run:
    workflows:
      - Cogni AI Agent
    types:
      - completed
permissions:
  contents: read
jobs:
  check:
    uses: FX31337/.github/.github/workflows/check.yml@master
    with:
      submodules: ${{ inputs.submodules || 'false' }}
